In [7]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
import numpy as np

In [4]:
df = pd.read_csv('/Users/cameronlefevre/Test-Repo/ClassMaterial/Unit3/data/housing.csv')

In [5]:
tree = DecisionTreeRegressor()

In [22]:
left = df[df.LSTAT < 9.67]
right = df[df.LSTAT >= 9.67]

In [23]:
root_error = np.mean((df['PRICE'] - df['PRICE'].mean())**2)

In [24]:
right_error = np.mean((right['PRICE'] - right['PRICE'].mean())**2)
left_error = np.mean((left['PRICE'] - left['PRICE'].mean())**2)

In [25]:
right_error

24.32308736092969

In [26]:
left_error

79.95297868897926

In [27]:
num_samples = df.shape[0]
right_samples = right.shape[0]
left_samples = left.shape[0]

In [28]:
num_samples

506

In [29]:
right_samples

298

In [30]:
left_samples

208

In [31]:
right_samples / num_samples * right_error

14.32466409793883

In [32]:
left_samples / num_samples * left_error

32.86604657570689

In [33]:
root_error - (right_samples / num_samples * right_error) - (left_samples / num_samples * left_error)

37.22884548251987

In [34]:
root_error

84.4195561561656

In [44]:
# initialize your algorithm
tree = DecisionTreeRegressor(max_depth=12)

In [45]:
# declare X & y
X = df.drop('PRICE', axis=1) #everything but the PRICE column
y = df['PRICE'] # just the PRICE column

tree.fit(X, y)

DecisionTreeRegressor(max_depth=12)

In [38]:
from prep import draw_tree

draw_tree(tree, X)

ModuleNotFoundError: No module named 'prep'

In [46]:
# this will go ahead and make predictions
df['Prediction'] = tree.predict(X)

In [47]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  PRICE  Prediction  
0  396.90   4.98   24.0   24.000000  
1  396.90   9.14   21.6   22.145455  
2  392.83   4.03   34.7   34.700000  
3  394.63   2.94   33.4   33.400000  
4  396.90   5.33   36.2   36.200000

In [42]:
df['PRICE'] - df['Prediction']

0     -3.427273
1     -0.029744
2      1.951220
3      0.651220
4      3.451220
         ...   
501   -5.027273
502   -1.029744
503   -8.848780
504   -5.427273
505   -9.729744
Length: 506, dtype: float64

In [48]:
tree.score(X,y)

0.9968875816437084

In [49]:
# boosting starts with a NAIVE prediction
naive_guess = y.mean()

In [51]:
# get the error column
gradient = y - y.mean()

In [52]:
# initialize a decision tree - it will usually be shallow
tree = DecisionTreeRegressor(max_depth=4)

In [53]:
# fit a tree on X and the gradient
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=4)

In [54]:
# Not predicting the value of Y, predicting the error of Y
tree.predict(X)

array([  3.68001419,  -1.7206676 ,  12.01119368,  12.01119368,
        12.01119368,   1.29059793,  -1.7206676 ,  -1.7206676 ,
        -1.7206676 ,  -1.7206676 ,  -1.7206676 ,  -1.7206676 ,
        -1.7206676 ,  -1.7206676 ,  -1.7206676 ,  -1.7206676 ,
         1.29059793,  -5.99372586,  -1.7206676 ,  -1.7206676 ,
        -5.99372586,  -1.7206676 ,  -5.99372586,  -5.99372586,
        -5.99372586,  -5.99372586,  -5.99372586,  -5.99372586,
        -1.7206676 ,   3.68001419,  -5.99372586,  -1.7206676 ,
        -5.99372586,  -5.99372586,  -5.99372586,  -1.7206676 ,
        -1.7206676 ,  -1.7206676 ,  -1.7206676 ,   7.70837015,
        12.01119368,   7.70837015,   1.29059793,   1.29059793,
        -1.7206676 ,  -1.7206676 ,  -1.7206676 ,  -1.7206676 ,
        -1.7206676 ,  -1.7206676 ,  -1.7206676 ,  -1.7206676 ,
         1.29059793,  -1.7206676 ,  -1.7206676 ,  12.01119368,
         1.29059793,   7.70837015,   1.29059793,  -1.7206676 ,
        -1.7206676 ,  -1.7206676 ,   1.29059793,   3.68

In [55]:
naive_guess += tree.predict(X)

In [57]:
gradient = y - naive_guess

In [58]:
gradient

0     -2.212821
1      0.787861
2      0.156000
3     -1.144000
4      1.656000
         ...   
501   -3.812821
502   -0.212139
503   -3.014286
504   -4.212821
505   -8.912139
Name: PRICE, Length: 506, dtype: float64

In [59]:
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=4)

In [60]:
tree.predict(X)

array([ 0.44221866,  0.44221866,  0.44221866,  0.44221866,  0.44221866,
        0.44221866,  0.44221866,  0.44221866, -0.84047839, -0.84047839,
       -0.84047839, -0.84047839,  0.44221866, -1.47038794, -1.47038794,
       -1.47038794, -1.47038794, -1.47038794, -3.29994958, -3.29994958,
       -3.29994958, -3.29994958, -3.29994958, -3.29994958, -1.47038794,
       -1.47038794, -1.47038794, -1.47038794, -1.47038794, -3.29994958,
       -3.29994958, -3.29994958, -3.29994958, -3.29994958, -3.29994958,
        0.44221866,  0.44221866,  0.44221866,  0.44221866,  0.44221866,
        0.44221866,  0.44221866,  0.44221866,  0.44221866,  0.44221866,
        0.44221866,  0.44221866,  0.44221866,  0.44221866, -0.84047839,
       -0.84047839, -0.84047839, -0.84047839, -0.84047839, -1.47038794,
       -0.84047839, -0.84047839, -0.84047839, -0.84047839, -0.84047839,
       -0.84047839, -0.84047839, -0.84047839, -0.84047839, -0.84047839,
       -0.84047839, -0.84047839, -0.84047839, -0.84047839, -0.84

In [61]:
naive_guess += tree.predict(X)

In [62]:
from sklearn.ensemble import GradientBoostingRegressor

In [63]:
gbm = GradientBoostingRegressor()

In [64]:
gbm.get_params()

{'alpha': 0.9,
 'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'ls',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'presort': 'deprecated',
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [65]:
gbm.fit(X, y)

GradientBoostingRegressor()

In [66]:
gbm.score(X, y)

0.975391831460784

In [67]:
gbm.feature_importances_

array([7.24141917e-03, 2.35860807e-04, 2.38121752e-03, 1.04510485e-04,
       7.54976801e-03, 1.45196036e-02, 5.71928899e-03, 1.31136141e-02,
       2.53913011e-03, 1.45537719e-02, 1.64359674e-02, 8.65636586e-03,
       7.04755018e-02, 8.36473980e-01])

In [68]:
X.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'Prediction'],
      dtype='object')